apiVersion: v1
kind: Secret
metadata:
  name: "ndb-nkp-2-81-secret"
type: Opaque
stringData:
  username: admin
  password: G8keeper!
---
apiVersion: v1
kind: Secret
metadata:
  name: "self-serve-postgres-secret"
type: Opaque
stringData:
  password: password-for-the-database-instance
  ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwZ7cWgwxvq/AYU3eSBqRwXpKL5ch9egNE31HBdt+Jtl/SRFHR2tv6e8Z4jy8EHy6D9JobNZg2iPEVrV8R+po6KYGMDggpJuAV9fgPbXo0L4fwct62TYLHnB7iXjbBUsjR2foWI58C8zY3ee+fdYEjEoz7pP8DwqHo4RUvUATxAjTMraWxq2n2NksUoHrwM9DboRh8TDKRogQtu8esPjfvRqds6U4VQfY+LfPPsbb/30nZKEFGedwr1lEjHxMEI7oTbW5etF1o+apWzXTH4ZKDLStZrR6OIyqADRm1I0zpW9O3Z0X8VUH1GvmBGHwiUXPzytfa3+xPDeQ3p1vXCecCd5MclufxP/W+reisNwTOY+GN3VVq0sTZnZFrEDl/yy9r+fvPLbRGSGCEP2CK+UlWpWcATi+MQNKWekHMQiI2BX0CUWKTr45BnKOj3b5GucNF6bLFchuPC8enzRfT6mbKEX2azv0rCK76Q3buJklrwexHwkfCBoYcs15aUkfTPac=